Update introduction.md
exercism/java pull request #2036
Opened 2021-10-02 07:51 UTC by myucesan

Added comparison operator example, removed the reference to truthy values as it will only confuse new programmers

# pull request

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

2021-10-02 15:31 UTC, jmrunkle requested changes
Do we also need to make similar changes to the about.md file?

2021-10-02 15:31 UTC, jmrunkle commented on concepts/numbers/introduction.md
> +Arithmetic is done using the standard arithmetic operators. Numbers can be compared using the standard numeric comparison operators (5 > 4 and 4 < 5) and the equality (`==`) and inequality (`!=`) ope
```suggestion
Arithmetic is done using the standard arithmetic operators. Numbers can be compared using the standard numeric comparison operators (eg. `5 > 4` and `4 <= 5`) and the equality (`==`) and inequality (`!=`) operators.
```

2021-10-03 12:15 UTC, myucesan commented
> Do we also need to make similar changes to the about.md file?

No, it already has examples.

2021-10-04 20:15 UTC, jmrunkle approved these changes

2021-10-04 20:15 UTC, merged