All @ignore decorators removed above tests in concept exercises
exercism/java pull request #2079
Opened 2021-12-23 15:59 UTC by AchalS-iglu

# pull request

Fix for issue [https://github.com/exercism/exercism/issues/6167](https://github.com/exercism/exercism/issues/6167)

All @ignore statements removed from concept exercises tests

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

2021-12-23 20:15 UTC, jmrunkle approved these changes

2021-12-23 20:20 UTC, jmrunkle requested changes
Actually, you still need to remove the unused imports of the Ignore annotation

2021-12-23 20:30 UTC, AchalS-iglu commented
> Actually, you still need to remove the unused imports of the Ignore annotation

Alright, gimmie 5!

2021-12-23 20:37 UTC, AchalS-iglu commented
Hopefully this helps! I am a complete noob at Java, I removed all the ignore import

2021-12-24 02:47 UTC, jmrunkle approved these changes

2021-12-24 02:48 UTC, merged