Clarify Instruction to state that characters that are not letters (in…
exercism/java pull request #2130
Opened 2022-06-15 13:06 UTC by emiliolg

…cluding digits, etc) should be removed.

Add a test that showed that more clearly.

# pull request

Doing Mentoring I noticed that the instructions do not specify that instructions are not clear about removing digits and so on. 
I checked the C# track and instructions were clear. So I update the Java instructions to reflect that.
I also add a test that an additional test to show removing no letters while keeping them.

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/master/POLICIES.md#event-checklist)

2022-06-15 22:14 UTC, andrerfcsantos requested changes
Looks cool, left some minor suggestions.

Note that when changing the tasks, [hints.md](https://github.com/exercism/java/blob/main/exercises/concept/squeaky-clean/.docs/hints.md) should also be modified, and the section names must match the names for the tasks in the instructions.

2022-06-15 22:14 UTC, andrerfcsantos commented on exercises/concept/squeaky-clean/src/test/java/SqueakyCleanTest.java
> +    public void remove_no_letters() {
```suggestion

    @Test
    public void keep_only_letters() {
```

Maybe this is a more appropriate name for the test?

2022-06-18 15:44 UTC, emiliolg reviewed
Fix hints.md

2022-06-19 10:20 UTC, andrerfcsantos approved these changes
Thanks for this.

2022-06-19 10:22 UTC, merged