Exercise stubs for missing exercises
exercism/java pull request #2319
Opened 2023-06-07 19:41 UTC by DWalz

Add Exercise Stubs for all exercises mentioned in [this comment](https://github.com/exercism/java/issues/2133#issuecomment-1566970411) except for `allergies` (#2303) and `pig-latin` (#2315) which are still pending.

I have used `final` for every function parameter, all classes are `package-private`.

2023-08-24 15:58 UTC, SleeplessByte commented
@DWalz 3 exercises are failing. Knapsack, Hangman, and Rest-Api. 

Can you check if this is "you" or something else? If it's something else we can merge this and fix it separately.

2023-08-26 07:56 UTC, sanderploegsma commented
> @DWalz 3 exercises are failing. Knapsack, Hangman, and Rest-Api.
> 
> Can you check if this is "you" or something else? If it's something else we can merge this and fix it separately.

I looked into the failures and two of them were caused by a Gradle configuration issue that had nothing to do with the individual exercise configs. I pushed a fix for that, because it's just made visible by the changes in this PR even though this issue was already present in `main`.

The Knapsack exercise still doesn't compile because it references a class `Item` that is not present in the stub. @DWalz if you could address this we can get this merged.

2023-08-26 12:31 UTC, DWalz commented
The `Item` class was indeed missing. I added it with the same implementation from the solution. I assume this class doesn't have to be implemented by the solver themselves.

2023-08-26 12:36 UTC, sanderploegsma requested changes
Nice work! I found two more small things to take care of though.

2023-08-26 12:36 UTC, sanderploegsma commented on exercises/practice/knapsack/src/main/java/Item.java
Any files you add should also be added in the exercise's `.meta/config.json` file, either in `files.solution` for files that should be edited as part of the exercise, or `files.editor` for read-only files that can be viewed by students in the online editor.

In this case since the class seems to be fully implemented already, please add it to the `files.editor` list.

2023-08-26 12:36 UTC, sanderploegsma commented on exercises/practice/queen-attack/src/main/java/Queen.java
Any files you add should also be added in the exercise's `.meta/config.json` file, either in `files.solution` for files that should be edited as part of the exercise, or `files.editor` for read-only files that can be viewed by students in the online editor.

In this case since the class needs to be implemented by the student, please add it to the `files.solution` list.

2023-08-26 12:51 UTC, sanderploegsma approved these changes
LGTM! @SleeplessByte do you want to have a final look?

2023-08-29 04:52 UTC, sanderploegsma commented
I’m guessing that’s a no 😉

2023-08-29 04:53 UTC, merged