Update karl's languages to use test runner v3 features
exercism/java pull request #2493
Opened 2023-09-26 16:08 UTC by aldotele

This PR addresses karl's languages task on issue #2356 

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

2023-09-26 19:42 UTC, sanderploegsma requested changes
I have left a bunch of comments this time. Most of them are suggestions on the naming of the tests, as I believe they can be a bit shorter and clearer.

The others are about the test cases themselves, I believe we can make them a bit better.

2023-09-26 19:42 UTC, sanderploegsma commented on exercises/concept/karls-languages/src/test/java/LanguageListTest.java
> +    @DisplayName("The isEmpty method returns true when no language was added to the list")
```suggestion
    @DisplayName("The isEmpty method returns true when the list contains no languages")
```

2023-09-26 19:42 UTC, sanderploegsma commented on exercises/concept/karls-languages/src/test/java/LanguageListTest.java
> +    @DisplayName("The addLanguage method correctly adds a language to the list so that list is no more empty")
```suggestion
    @DisplayName("The isEmpty method returns false after adding a language to the list")
```

2023-09-26 19:42 UTC, sanderploegsma commented on exercises/concept/karls-languages/src/test/java/LanguageListTest.java
> +    @DisplayName("The removeLanguage method correctly removes a language from the list")
This test is a bit weird: it uses `containsLanguage` to check whether the language was removed, but this method is not yet implemented in task 3.

I would suggest refactoring the test method to only use methods implemented so far, by making it

1. Add a language
2. Remove that same language
3. Asserting that the list is empty again.

2023-09-26 19:42 UTC, sanderploegsma commented on exercises/concept/karls-languages/src/test/java/LanguageListTest.java
> +    @DisplayName("The firstLanguage method correctly retrieves the first language that was added to the list")
```suggestion
    @DisplayName("The firstLanguage method returns the first language that was added to the list")
```

2023-09-26 19:42 UTC, sanderploegsma commented on exercises/concept/karls-languages/src/test/java/LanguageListTest.java
> +    @DisplayName("The count method returns the correct number of languages that were added to the list")
```suggestion
    @DisplayName("The count method returns the number of languages in the list")
```

2023-09-26 19:42 UTC, sanderploegsma commented on exercises/concept/karls-languages/src/test/java/LanguageListTest.java
> +    @DisplayName("The count method returns 0 in case no language was added to the list")
```suggestion
    @DisplayName("The count method returns 0 when the list is empty")
```

2023-09-26 19:42 UTC, sanderploegsma commented on exercises/concept/karls-languages/src/test/java/LanguageListTest.java
> +    }
I would suggest refactoring these tests to make them a bit simpler, something like this:

```java
@Test
@Tag("task:6")
@DisplayName("The containsLanguage returns true when the language is in the list")
public void containsLanguage() {
     languageList.addLanguage("Java");

    assertThat(languageList.containsLanguage("Java")).isTrue();
}

@Test
@Tag("task:6")
@DisplayName("The containsLanguage returns false when the language is not in the list")
public void doesNotContainLanguage() {
    languageList.addLanguage("Kotlin");

    assertThat(languageList.containsLanguage("Java")).isFalse();
}
```

2023-09-26 19:42 UTC, sanderploegsma commented on exercises/concept/karls-languages/src/test/java/LanguageListTest.java
> +    @DisplayName("The isExciting method returns true after Java was added to the list")
```suggestion
    @DisplayName("The isExciting method returns true when the list contains Java")
```

2023-09-26 19:42 UTC, sanderploegsma commented on exercises/concept/karls-languages/src/test/java/LanguageListTest.java
> +    @DisplayName("The isExciting method returns true after Kotlin was added to the list")
```suggestion
    @DisplayName("The isExciting method returns true when the list contains Kotlin")
```

2023-09-26 19:42 UTC, sanderploegsma commented on exercises/concept/karls-languages/src/test/java/LanguageListTest.java
> +    @DisplayName("The isExciting method returns false when neither Java nor Kotlin were added to the list")
```suggestion
    @DisplayName("The isExciting method returns false when the list contains neither Java nor Kotlin")
```

2023-09-27 08:39 UTC, aldotele commented
Just commited the enhancements, thank you for the review!

2023-09-27 09:03 UTC, sanderploegsma approved these changes
LGTM, thanks!

2023-09-27 09:03 UTC, merged