Fixed typos
exercism/java pull request #2585
Opened 2023-11-26 15:55 UTC by smicaliz

Closes #2561 

I checked and fixed some other typos.

2023-11-26 16:38 UTC, sanderploegsma requested changes
One thing to take care of, the rest looks good! 👍

2023-11-26 16:38 UTC, sanderploegsma commented on exercises/concept/wizards-and-warriors/.docs/introduction.md
This file is actually generated by the `introduction.md.tpl` template file, so you should make these changes in the source document instead and then regenerate this file.

The source file is `concepts/inheritance/introduction.md`, and you can use the configlet to regenerate the file:

```sh
bin/configlet generate
```

2023-11-28 14:00 UTC, sanderploegsma requested changes

2023-11-28 14:00 UTC, sanderploegsma commented on concepts/inheritance/introduction.md
> +        animal.bark();
What is the reason for adding this indentation? I don't think it makes the snippet more readable. Could you revert it please?

2023-11-28 16:33 UTC, smicaliz commented
Actually I did not any of that 2 modifications. I think there was something auto or I didn't pay enough attention. I should be more attentive. It's fixed. Thanks the review!

2023-11-28 16:34 UTC, sanderploegsma approved these changes
LGTM 👍 Thanks for the fix!

2023-11-28 16:35 UTC, merged