Add maps concept
exercism/java pull request #2593
Opened 2023-12-04 18:55 UTC by smcg468

# pull request

This issue addresses #2583 

- Renamed the exercise from 'high-score' to 'arcade-high score' to avoid clashing of exercise names
- Added 'maps' to the practises and prerequisites for the 7 exercises listed in the issue
- Changed the prerequisites for the arcade-high-score concept exercise from what was on the elixir track which was

          "lists",
          "tuples",
          "anonymous-functions",
          "default-arguments"

to

           "numbers"
           "strings"

- Could also add an howManyPlayers task to utilise the .size() method if it would help, or maybe best to keep it consistent with the elixir track. 

Let me know of any changes you'd like me to make.
---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

2023-12-04 21:02 UTC, sanderploegsma commented
Awesome! I'll try to review this sometime this week 👍

2023-12-09 14:48 UTC, sanderploegsma requested changes
Thanks for picking this up! It already looks very good, and I left a bunch of comments mainly related to making the exercise a little bit more object-oriented, which is more in line with the Java track's policies.

Could you have a look at them and request a new review when you have addressed them?

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/settings.gradle
> +include 'concept:arcade-high-score'
The list of exercises is now sorted alphabetically to limit the number of merge conflicts occurring when multiple people are working on new concept exercises at the same time.

Could you move this entry to the appropriate place?

2023-12-09 14:48 UTC, sanderploegsma commented on concepts/maps/introduction.md
In my opinion this introduction into Maps should focus more on the basic operations when working with maps. Specifically, I think it should show:

- How to create a new Map instance.
- How to set values using the `put` method.
- How to retrieve values using the `get` method.

To me, the `keySet` and `values` methods are OK to mention in the `about.md`, but should not be introduced until a student knows how to interact with the map contents directly.

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/src/main/java/ArcadeHighScore.java
Personally I'd like to change this exercise to be a little bit more object-oriented. I have the following reference implementation in mind, what do you think?

```java
class ArcadeHighScore {

    private Map<String, Integer> highScores = new HashMap<>();

    Map<String, Integer> getHighScores() {
        return highScores;
    }

    void addPlayer(String name, Integer score) {
        highScores.put(name, score);
    }

    void removePlayer(String name) {
        highScores.remove(name);
    }

    void resetScore(String name) {
        highScores.put(name, 0);
    }

    void updateScore(String name, Integer score) {
        Integer oldScore = highScores.getOrDefault(name, 0);
        highScores.put(name, oldScore + score);
    }

    Set<String> getPlayers() {
        return highScores.keySet();
    }
}
```

The first task would then cover defining the private `highScores` field and returning it in the `getHighScores()` method. The other tasks should speak for themselves.

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/src/test/java/ArcadeHighScoreTest.java
> +    private final ArcadeHighScore arcadeHighScore = new ArcadeHighScore();
You probably want to create a new instance for every test using `@BeforeEach` to make sure the SUT doesn't retain any state from a previous test, this makes the tests easier to reason about, also for students!

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.docs/instructions.md
> +// => {}
```suggestion
ArcadeHighScore arcadeHighScore = new ArcadeHighScore();
arcadeHighScore.getHighScores();
// => {} 
```

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.docs/instructions.md
> +// => {Dave Thomas=0}
```suggestion
arcadeHighScore.addPlayer("Dave Thomas", 0);
arcadeHighScore.getHighScores();
// => {Dave Thomas=0}
```

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.docs/instructions.md
> +- The second argument is the players score as an Integer.
```suggestion
To add a player to the high score map, implement the `ArcadeHighScore.addPlayer()` method, which takes the player's name and score as arguments.

When called, it should store the player and their score in the `highScores` map.
```

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.docs/instructions.md
> +- The argument is the key of the item, in this case the name of the player.
```suggestion
To remove a player from the high score map, implement the `ArcadeHighScore.removePlayer()` method, which takes the player's name as an argument.

When called, it should remove the entry associated to the player from the `highScores` map.
```

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.docs/instructions.md
> +- The argument is the players name.
```suggestion
To reset a player's score, implement the `ArcadeHighScore.resetScore()` method, which takes the player's name as an argument.

When called, it should reset the score of the player to `0` in the `highScores` map.
```

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.docs/instructions.md
> +// => {}
```suggestion
arcadeHighScore.removePlayer("Dave Thomas");
arcadeHighScore.getHighScores();
// => {}
```

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.docs/instructions.md
> +// => (Dave Thomas=0);
```suggestion
arcadeHighScore.resetScore("Dave Thomas");
arcadeHighScore.getHighScores();
// => (Dave Thomas=0);
```

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.docs/instructions.md
> +The function should also work if the player doesn't have a previous score - assume the previous score is 0.
```suggestion
To update a player's score by adding to the previous score, implement `ArcadeHighScore.updateScore()` method, which takes the player's name and their new score as arguments.

When called, it should _add_ the new score to the player's previous score stored in the `highScores` map.
If the player doesn't have a previous score, assume the previous score is `0`.
```

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.docs/instructions.md
> +// => {Lionel Messi=88, Dave Thomas=57}
```suggestion
ArcadeHighScore arcadeHighScore = new ArcadeHighScore();

// Adding a players score to update
arcadeHighScore.addPlayer("Lionel Messi", 48);
arcadeHighScore.updateScore("Lionel Messi", 40);
arcadeHighScore.getHighScores();
// => {Lionel Messi=88}

// Updating a players score who doesn't have a previous score
arcadeHighScore.updateScore("Dave Thomas", 57);
arcadeHighScore.getHighScores();
// => {Lionel Messi=88, Dave Thomas=57}
```

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.docs/instructions.md
> +To get a list of players, define the `ArcadeHighScore.listOfPlayers()`, which takes no arguments:
```suggestion
To get a list of players, implement the `ArcadeHighScore.getPlayers()` method.

When called, it should return a collection containing all player's names currently stored in the `highScores` map.
```

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.docs/instructions.md
> +// => {Lionel Messi, Dave Thomas}
```suggestion
arcadeHighScore.getPlayers();
// => {Lionel Messi, Dave Thomas}
```

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.meta/design.md
> +- Know the main differences in `HashMap`, `LinkedHashMap` and `TreeMap`.
Note on these objectives: they should cover the learning objectives from the _exercise_, not the _concept_. I believe this exercise doesn't cover the different implementations of the `Map` interface, nor how to retrieve all items in a map.

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.meta/design.md
> +- `SortedMap`
We can probably cover all future additions of `Map` implementations in Java by summarizing this as "Other implementations of the `Map` interface"

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/.meta/design.md
> +- `strings`: know how to use string formatting.
Technically I don't think string formatting is used in this exercise, so maybe `strings` doesn't have to be a prerequisite.

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/src/test/java/ArcadeHighScoreTest.java
> +        assertNotNull(arcadeHighScore.defineMap());
We should probably (also) check that it's empty.

2023-12-09 14:48 UTC, sanderploegsma commented on exercises/concept/arcade-high-score/src/test/java/ArcadeHighScoreTest.java
> +    public void updateScore() {
I think we need to add a second test for this task that verifies the requirement when `updateScore` is called with a player that doesn't exist in the map yet.

2023-12-26 19:36 UTC, sanderploegsma commented
@smcg468 Are you still working on this? Leave a comment if you are, otherwise I'm going to close this due to inactivity.

2023-12-27 19:42 UTC, smcg468 commented
> @smcg468 Are you still working on this? Leave a comment if you are, otherwise I'm going to close this due to inactivity.

Yes still working on this, been quite busy over Christmas but should get back to it soon

2024-02-21 22:04 UTC, smcg468 commented
@sanderploegsma Sorry yes will get back to it this weekend

2024-02-22 08:04 UTC, sanderploegsma commented
Take your time! I didn't mean to rush you, but I figured you may have lost track of this PR 😉

2024-04-02 20:18 UTC, manumafe98 commented
Hey @smcg468! we will like to know if you need help finishing this PR! it's an interesting concept to be added to the java track, so if you are busy with work we can give you a hand with it! Thanks for your time 😃

2024-05-07 06:49 UTC, sanderploegsma commented
@smcg468 I see you've been busy, nice!

Since some of the CI jobs are still failing I'm going to assume that you're still working on addressing the feedback. Just make sure to hit the 're-request review' button on this PR once you're done, so I know it's ready for another look. 😉

2024-07-12 01:02 UTC, manumafe98 commented
hey @smcg468 do you need some help with this pr?

2024-09-01 21:01 UTC, closed without merging