Add analyzer feedback for Annalyns Infiltration
exercism/java pull request #2700
Opened 2024-01-31 14:16 UTC by kahgoh

# pull request

closes #2669

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

2024-01-31 16:10 UTC, manumafe98 requested changes
Checking on the Javascript analyzer [approach](https://github.com/exercism/javascript/blob/main/exercises/concept/annalyns-infiltration/.meta/design.md#analyzer) I would say that we could be more explicit on some actionables, I like the topics already created, but maybe we could add a couple more, I also would like your opinion on this one @sanderploegsma 

The if statement in the method seem to be treated as essential as  well, check [this](https://github.com/exercism/javascript-analyzer/blob/main/src/analyzers/concept/annalyns-infiltration/index.ts)

2024-01-31 18:54 UTC, sanderploegsma commented
I think that given the scope of the concept and the exercise, we should steer students towards a solution that _only_ uses boolean operators (`&&`, `||` and `!`). If a solution uses if-statements, ternary expressions or comparison operators and boolean literals, I think the analyzer comments should be of type `essential`.

In terms of additional comments, I can think of only one thing, and that is unnecessary parentheses in the final method. If there is a consistent way to check this, could be an `informative` comment if the rest of the solution doesn't receive any feedback.

2024-02-01 14:08 UTC, kahgoh commented
Making them essential sounds good to me ;) 

Thanks for pointing me to the Javascript analyzer @manumafe98. I've tried taking some inspiration from there for the wording and added something about the unnecessary parentheses.

2024-02-01 15:18 UTC, manumafe98 commented
> Thanks for pointing me to the Javascript analyzer @manumafe98. I've tried taking some inspiration from there for the wording and added something about the unnecessary parentheses.

Np! this is already looking great!

2024-02-01 19:38 UTC, sanderploegsma commented on exercises/concept/annalyns-infiltration/.meta/design.md
> +                ```
This snippet is not rendering correctly: https://github.com/exercism/java/blob/c6c6889a24742828d4904b6b8284181359cbc29c/exercises/concept/annalyns-infiltration/.meta/design.md

Try indenting it with 2 spaces and leave a blank line before and after it. That should make it part of the list item and fix the rendering.

2024-02-02 13:23 UTC, manumafe98 approved these changes

2024-02-02 13:24 UTC, merged