Update typo in instructions.md
exercism/java pull request #2725
Opened 2024-02-06 18:34 UTC by jkriesp

# pull request

Quick typo fix

---

Reviewer Resources:

[Track Policies](https://github.com/exercism/java/blob/main/POLICIES.md#event-checklist)

2024-02-06 18:46 UTC, manumafe98 requested changes
https://github.com/exercism/java/blob/eca0604d30bf5c250711f3237a7e65cf0c154063/exercises/concept/need-for-speed/.docs/instructions.md?plain=1#L11
Can you please fix the ``remote controller`` mentioned there as well? Thanks!

2024-02-07 07:34 UTC, jkriesp commented
> https://github.com/exercism/java/blob/eca0604d30bf5c250711f3237a7e65cf0c154063/exercises/concept/need-for-speed/.docs/instructions.md?plain=1#L11
> 
> Can you please fix the `remote controller` mentioned there as well? Thanks!

Should be good now.

2024-02-07 13:02 UTC, manumafe98 commented
LGTM!

2024-02-07 13:03 UTC, manumafe98 approved these changes

2024-02-07 13:03 UTC, merged